from __future__ import annotations

"""Environment configuration for WidowX PCB push into magazine slot.

Single push task: open-jaw trailing-edge approach, then +Y slide to slot mouth.

Registered variant (see ``__init__.py``):
  - ``Isaac-WidowX-PCB-Push-v0``
"""

import os
from isaaclab.utils import configclass
from isaaclab.envs import ManagerBasedRLEnvCfg
from isaaclab.assets import ArticulationCfg, AssetBaseCfg, RigidObjectCfg
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.managers import (
    CurriculumTermCfg,
    EventTermCfg,
    ObservationGroupCfg,
    ObservationTermCfg,
    RewardTermCfg,
    SceneEntityCfg,
    TerminationTermCfg,
)
from isaaclab.controllers import OperationalSpaceControllerCfg
from isaaclab.actuators import ImplicitActuatorCfg
import isaaclab.sim as sim_utils
import isaaclab.envs.mdp as mdp
from .mdp_custom import (
    gripper_midpoint_position_env,
    gripper_jaw_pad_midpoint_position_env,
    pcb_leading_short_edge_center_env,
    pcb_trailing_short_edge_center_env,
    joint_pos_rel_episode_reset,
    gripper_opening_normalized,
    pcb_leading_edge_insertion_proximity_reward,
    pcb_leading_edge_push_axis_approach_progress_gated,
    pcb_push_axis_velocity_reward_gated,
    action_rate_l2,
    straddle_lateral_gap_shaping,
    slide_success_bonus_reward,
    slide_leading_edge_travel_milestone_bonus,
    straddle_tip_mid_thickness_shaping_gated,
    straddle_trailing_face_bounded_approach_reward,
    straddle_finger_trailing_width_proximity,
    arm_joint_home_deviation_penalty,
    reset_pcb_on_guide_rails_randomized,
    hold_gripper_open,
    pcb_to_target_error_obs,
    pcb_insertion_orientation_obs,
    reset_robot_joints_to_values,
    slide_success,
    slide_pcb_yaw_xy_alignment_shaping,
    slide_pcb_yaw_sin_obs,
    slide_finger_push_axis_delta_obs,
    WidowXTaskSpaceImpedanceActionCfg,
    pcb_root_height_below_env_minimum,
    pcb_tilt_beyond_limit,
    pcb_long_axis_vertical_component_exceeds,
    gripper_mid_thickness_offset_obs,
    gripper_trailing_edge_error_obs,
    gripper_pinch_orientation_cos_obs,
    pcb_moving_backward_termination,
    push_gripper_debug_step,
    push_gripper_debug_curriculum,
    push_gripper_debug_monitor_reward,
    vic_arm_stiffness_normalized_obs,
    vic_arm_damping_normalized_obs,
    arm_joint_torque_normalized_obs,
    arm_joint_stall_obs,
)

# Conversion: mm to meters
PCB_X = 240.0 * 0.001
PCB_Y = 78.5 * 0.001
PCB_Z = 0.001
PCB_MASS_KG = 0.05
_PCB_HALF_WIDTH_M = PCB_Y * 0.5
_SHORT_EDGE_WIDTH_WEIGHT = 3.0
ASSET_DIR = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Assembly (magazine + stand + conveyor) placement  — env_v6 / assembly_6
# ---------------------------------------------------------------------------
# pcb_insertion_env.usd is generated by usd_model/env_v6/convert_to_usd.py.
# Meshes are FK-baked in the part_1_1 assembly frame (Onshape hanging-node offset removed).
# Guide rails (Part_1_7.stl), side belts (Part_1_2.stl), short axles omitted.
#
# Rotation: -90 deg about world Z (quaternion w=0.707, z=-0.707).
#   root +Y  →  world +X
#   root -X  →  world +Y   (push direction)
#   root +Z  →  world +Z
#
# env_v6 FK key positions in part_1_1 frame (from convert_to_usd.py):
#   chip visual centre : root ( 0.034, -0.473,  0.149)
#   chip belt top Z    : root  0.150
#   magazine centre    : root (-0.210, -0.201,  0.093)
#
# With _MAG_POS=(tx, ty, tz) env-local coordinates are:
#   env_x = root_Y + tx,   env_y = -root_X + ty,   env_z = root_Z + tz
#
# _MAG_POS kept at prior Sim-tuned placement (not re-derived from env_v6 FK).
_MAG_POS      = (0.255, 0.094, 0.0)
_MAG_ROT_WXYZ = (0.7071068, 0.0, 0.0, -0.7071068)   # -90 deg about world Z

# World-frame push direction: root -X  →  world +Y.
PUSH_AXIS_WORLD = (0.0, 1.0, 0.0)

# ---------------------------------------------------------------------------
# Robot — independent of PCB / slot geometry (tune in Isaac Sim)
# ---------------------------------------------------------------------------
# Base beside the conveyor; +90° CCW yaw about world +Z (``_ROBOT_BASE_ROT_WXYZ``).
_ROBOT_BASE_POS = (0.045, -0.30, 0.05)
# +90° CCW about world +Z (w, x, y, z).
_ROBOT_BASE_ROT_WXYZ = (0.7071068, 0.0, 0.0, 0.7071068)

# wxai carriage: physical jaw span (m) ≈ ``left_carriage_joint`` × scale (q=0.02 → 40 mm).
_GRIPPER_JOINT_TO_SPAN_M = 2.0
_PUSH_JAW_SPAN_M = 0.030
_PUSH_OPEN_WIDTH_M = _PUSH_JAW_SPAN_M / _GRIPPER_JOINT_TO_SPAN_M

_ROBOT_HOME_JOINT_POS = {
    "joint_0": 0.0,    # base yaw — nearly 0 (PCB is almost directly in +X from base)
    "joint_1": 0.25,    # shoulder pitch down
    "joint_2": 0.15,    # elbow bend
    "joint_3": -0.25, # wrist pitch
    "joint_4": 0.0,
    "joint_5": 0.0,    # wrist yaw — face toward conveyor (+Y approach)
    "left_carriage_joint": _PUSH_OPEN_WIDTH_M,
}
# PCB pose offsets (env-local m / world-Z yaw rad) applied on top of ``_PCB_INIT_POS`` / ``_PCB_INIT_ROT_WXYZ``.
_PCB_POS_OFFSET_RANGES = {
    "x": (-0.002, 0.002),
}
_PCB_YAW_OFFSET_RANGE = (-0.002, 0.002)
_GRIPPER_OPEN_WIDTH_M = _PUSH_OPEN_WIDTH_M
# Distal offset from ``gripper_left``/``gripper_right`` body origin to contact pad tip (wrist→jaw).
_GRIPPER_TIP_OFFSET_M = 0.06

# ---------------------------------------------------------------------------
# Conveyor + slot — independent of robot (prior Sim tuning; env_v6 USD at _MAG_POS above)
# ---------------------------------------------------------------------------
_CONVEYOR_CENTER_X_ENV = 0.056     # chip / conveyor centre X in env frame
# PCB lane X for straddle / slide (not magazine bbox centre X ≈ 0.277).
_CONVEYOR_SURFACE_Z = 0.147        # conveyor top Z (chip FK z + _MAG_POS[2] − PCB_Z/2)
# Push spawn height (+50 mm above belt clears guide-rail meshes; lower than +70 mm → less knock-off).
_PCB_CENTER_Z_ENV = _CONVEYOR_SURFACE_Z + PCB_Z * 0.5
# Rail contact: PCB centre when the bottom sits on guide rails (~78 mm above belt top).
_RAIL_CENTER_Z_ENV = _CONVEYOR_SURFACE_Z + PCB_Z * 0.5
# Straddle terminal states are saved near the straddle spawn centre (above belt, not on rails).
_PUSH_BUFFER_Z_REFERENCE_ENV = _PCB_CENTER_Z_ENV
# Sample buffer rows whose saved PCB Z is near the straddle reference height.
_PUSH_BUFFER_MAX_Z_DELTA_M = 0.025
# Slide buffer sampling: skip straddle rows that are already tilted / edge-on.
_SLIDE_BUFFER_MAX_TILT_PENALTY = 0.04
# _SLIDE_WRIST_MAX_PITCH_DEG = 30.0   # wrist→jaw elevation allowed above horizontal push plane
# _SLIDE_WRIST_PITCH_SOFT_DEG = 18.0  # smooth falloff beyond max pitch

# Gripper finger–PCB contact (multiply mode with PCB material in sim).
_GRIPPER_FINGER_STATIC_FRICTION = 4.0
_GRIPPER_FINGER_DYNAMIC_FRICTION = 3.2
_GRIPPER_ACTUATOR_STIFFNESS = 1000.0
_GRIPPER_ACTUATOR_DAMPING = 25.0

# Contact softening — lower depenetration / friction / stiff solver to reduce PCB bounce on rails.
_PCB_MAX_DEPENETRATION_VELOCITY = 0.05
_ROBOT_MAX_DEPENETRATION_VELOCITY = 0.05
_PCB_CONTACT_OFFSET_M = 0.0001
_PCB_REST_OFFSET_M = 0.0001
_PCB_STATIC_FRICTION = 0.7   # FR4 PCB surface (was 4.0 — too high, prevented jaw from sliding past trailing edge)
_PCB_DYNAMIC_FRICTION = 0.5  # kinetic (was 3.2)
_PCB_SOLVER_POS_ITERATIONS = 24
_PCB_SOLVER_VEL_ITERATIONS = 12
_PCB_LINEAR_DAMPING = 0.4
_PCB_ANGULAR_DAMPING = 0.45
_SIM_DEFAULT_STATIC_FRICTION = 2.0
_SIM_DEFAULT_DYNAMIC_FRICTION = 1.6
_SIM_MIN_POS_ITERATIONS = 6
_SIM_MIN_VEL_ITERATIONS = 2

# ---------------------------------------------------------------------------
# PCB — derived only from conveyor + slot (not from robot / gripper)
# ---------------------------------------------------------------------------
_PCB_FRONT_EDGE_GAP_M = 0.030      # front edge (toward +Y) this far before slot mouth

# body +X (long) || world +Y; centre on conveyor, bottom on belt top
_PCB_INIT_POS = (
    _CONVEYOR_CENTER_X_ENV,
    0.10 - _PCB_FRONT_EDGE_GAP_M,
    _PCB_CENTER_Z_ENV,
)

_PCB_INIT_ROT_WXYZ = (0.7071068, 0.0, 0.0, 0.7071068)

# Terminate when PCB falls well below the rail straddle height (tolerate push wobble).
_PCB_TERMINATE_MIN_HEIGHT_ENV = _CONVEYOR_SURFACE_Z - 0.025

# ---------------------------------------------------------------------------
# Magazine (insert target) geometry — Sim-tuned at _MAG_POS above (env_v6 USD).
# Env-local frame (meters):
#   X: [ 0.233,  0.321]  centre 0.277   (slot shifted +233 mm vs env_v3 centre 0.044)
#   Y: [ 0.228,  0.472]  bbox centre 0.350; slot entry (near face) ≈ 0.198 m (Sim-measured)
#   Z: [ 0.034,  0.178]
# ---------------------------------------------------------------------------
# _MAG_CENTER_X_ENV = 0.277      # magazine bbox centre X (env-local); lane X is _CONVEYOR_CENTER_X_ENV
# _MAG_CENTER_Y_ENV = 0.350      # magazine geometric centre Y (env-local)
_MAG_Y_NEAR_FACE_ENV = 0.207   # slot entry plane toward conveyor — leading edge enters here (Sim-measured)
_MAG_Y_FAR_FACE_ENV = 0.472    # magazine back wall — PCB leading edge seats just before here

# Leading-edge targets at far / near magazine faces (lane X, not magazine bbox centre X).
_HALF_LENGTH_M = PCB_X * 0.5

# Pure +Y slide gate: max PCB root off-axis speed sqrt(v_x² + v_z²) for state / velocity credit.
_SLIDE_PUSH_APPROACH_MAX_STEP_M = 0.005
# Leading-edge Z lift above episode-start height before exponential penalty (slide phase).
_SLIDE_LEAD_EDGE_MAX_LIFT_M = 0.004
_SLIDE_LEAD_EDGE_MAX_PENALTY_EXCESS_M = 0.02
# Legacy effort scale (JointEffortActionCfg / ActionsCfgSlide). Push uses VIC below.
_ARM_EFFORT_SCALE = {
    "joint_0": 4.0,
    "joint_1": 12.0,
    "joint_2": 12.0,
    "joint_3": 12.0,
    "joint_4": 10.0,
    "joint_5": 10.0,
}
# Task-space OSC (Push): policy [Δxyz, Δrpy, K_task, ζ_task] → 18-dim action (pose_rel + variable impedance).
_ARM_TASK_POSITION_SCALE = 0.05
_ARM_TASK_ORIENTATION_SCALE = 0.05
# Push/straddle: translate EE only — lock task-space rotation (rx, ry, rz) to stop early spin.
_ARM_TASK_MOTION_AXES = (1, 1, 1, 0, 0, 0)
_ARM_TASK_STIFFNESS_LIMITS = (50.0, 400.0)
_ARM_TASK_DAMPING_RATIO_LIMITS = (0.6, 2.0)
_ARM_TASK_DEFAULT_STIFFNESS = 150.0
_ARM_TASK_DEFAULT_DAMPING_RATIO = 1.2
# OSC body frame: wrist link (``link_6``); pad-tip frame uses ``body_offset`` below.
_EE_OSC_BODY_NAME = "link_6"
# Sim-to-real torque / stall obs (maps to motor current + encoder velocity on hardware).
_ARM_TORQUE_OBS_SCALE_NM = 3.0
_ARM_STALL_VEL_EPS_RAD_S = 0.05
_ARM_JOINT_OBS_ENT = SceneEntityCfg("robot", joint_names=["joint_[0-5]"])
# Gripper carriage: prismatic joint [N].  Raised for stronger closing torque once straddle opens.
_GRIPPER_EFFORT_SCALE = 10.0

# Conveyor lane lateral penalties (centre X defined above with conveyor constants).
_LANE_INNER_HALF_WIDTH_M = 0.025
_LANE_X_EXP_SCALE_M = 0.004
_LANE_X_MAX_EXCESS_M = 0.020
# Push credit only when trailing-edge straddle quality exceeds this (``pcb_between_gripper_fingers``).
_PUSH_JAW_GATE_MIN = 0.3

# Terminal-state buffers (Sequential Dexterity chaining).
_PUSH_STATES_PATH = os.path.join(ASSET_DIR, "data", "push_terminal_states.npz")
# Slide success: leading short-edge centre at magazine back (+Y); mouth for approach shaping.
_SLIDE_MOUTH_Y_MARGIN_M = 0.015
_SLIDE_MOUTH_LEAD_Y_ENV = _MAG_Y_NEAR_FACE_ENV - _SLIDE_MOUTH_Y_MARGIN_M
_SLIDE_SUCCESS_LEAD_Y_TOLERANCE_M = 0.015
# Success / milestone terminus: leading edge near magazine back wall (slide +Y direction).
_SLIDE_SUCCESS_LEAD_Y_ENV = _MAG_Y_FAR_FACE_ENV - _SLIDE_SUCCESS_LEAD_Y_TOLERANCE_M
_SLIDE_MOUTH_LEAD_X_ENV = _CONVEYOR_CENTER_X_ENV
_SLIDE_BELT_CENTER_Z_ENV = _RAIL_CENTER_Z_ENV  # milestones / rail Z shaping only
_SLIDE_SUCCESS_TARGET_LEAD_XY_ENV = (
    _SLIDE_MOUTH_LEAD_X_ENV,
    _SLIDE_SUCCESS_LEAD_Y_ENV,
)
_SLIDE_SUCCESS_LEAD_XY_TOLERANCE_M = (
    0.003,
    _SLIDE_SUCCESS_LEAD_Y_TOLERANCE_M,
)
_SLIDE_MAX_GRIPPER_GAP_M = PCB_Z * 2.0  # ``left_carriage_joint`` must stay below this at success
_SLIDE_APPROACH_LEAD_XYZ_ENV = (
    _SLIDE_MOUTH_LEAD_X_ENV,
    _SLIDE_MOUTH_LEAD_Y_ENV,
    _PCB_CENTER_Z_ENV,
)
# One-shot travel milestones (fraction of episode-start → success leading-edge +Y).
_SLIDE_TRAVEL_MILESTONE_FRACTIONS = (0.25, 0.5, 0.75, 0.875, 0.95)
# Milestone credit: lead X ±spawn drift; lead Z near belt-top centre height.
_SLIDE_MILESTONE_MAX_LEAD_X_DRIFT_M = 0.02
_SLIDE_MILESTONE_MAX_LEAD_Z_DRIFT_M = 0.02
# Slide +Y progress: no credit while PCB lifts / skids off-axis (anti crawl-and-lift).
_SLIDE_PUSH_MAX_OFF_AXIS_SPEED_M_S = 0.020
# Straddle hold + yaw correction during slide (open gripper, ±20 mm width targets).
_SLIDE_STRADDLE_HOLD_STD_M = 0.030
_SLIDE_FINGER_Y_SYNC_STD_M = 0.004
_SLIDE_YAW_GOOD_COS = 0.995
_SLIDE_YAW_BAD_COS = 0.970
_SLIDE_YAW_ASYM_STD_M = 0.006
_SLIDE_YAW_ASYM_GAIN_M = 0.015
_SLIDE_GRIPPER_NOMINAL_SPAN_M = 0.040
_SLIDE_GRIPPER_MAX_OPEN_MULT = 1.35
_SLIDE_GRIPPER_SPAN_SIGMA_M = 0.006
_SLIDE_GRIPPER_JOINT_MIN = 0.012   # ~24 mm span
_SLIDE_GRIPPER_JOINT_MAX = 0.027   # ~54 mm span
_SLIDE_GRIPPER_ACTION_SCALE = 0.0015
_SLIDE_GOAL_LEAD_XYZ_ENV = (
    _SLIDE_MOUTH_LEAD_X_ENV,
    _SLIDE_SUCCESS_LEAD_Y_ENV,
    _PCB_CENTER_Z_ENV,
)
# Straddle failure terminations — slightly looser than the old 0.10 / 0.40 while ``pcb_tilt_penalty`` shapes approach.
_PUSH_MAX_TILT_PENALTY = 0.11
_PUSH_MAX_LONG_AXIS_ABS_Z = 0.50

# Shared SceneEntityCfg snippets (reward / event params).
_PCB_ENT = SceneEntityCfg("pcb")
_ROBOT_ENT = SceneEntityCfg("robot")
_LEFT_FINGER = SceneEntityCfg("robot", body_names="gripper_left")
_RIGHT_FINGER = SceneEntityCfg("robot", body_names="gripper_right")
_GRIPPER_JOINT = SceneEntityCfg("robot", joint_names=["left_carriage_joint"])
_WRIST_BODY = SceneEntityCfg("robot", body_names="link_6")


def _gripper_wrist_kwargs() -> dict:
    """Wrist body cfg only (observations / orientation terms)."""
    return {"wrist_body_cfg": _WRIST_BODY}


def _gripper_kinematics_kwargs() -> dict:
    """Wrist body + pad-tip distal offset for contact-point rewards / straddle geometry."""
    return {**_gripper_wrist_kwargs(), "tip_offset_m": _GRIPPER_TIP_OFFSET_M}

# Minimum jaw span along the trailing short-edge (width) axis for a valid straddle.
_MIN_STRADDLE_SEP_M = 0.030

# Far-field height gate on along rewards — along credit scales with midpoint Z vs PCB centre.
_ALONG_HEIGHT_GATE_STD_M = 0.06

# Straddle finger targets along trailing edge (±offset from centre).
_PUSH_GAP_LEFT_M = 0.015
_PUSH_GAP_RIGHT_M = 0.015
_PUSH_FINGER_OFFSET_M = 0.015
# Approach shaping (finger_proximity): wide σ so gradient is active from ~10–15 cm behind edge.
_PUSH_PROXIMITY_STD_M = 0.10
# Success / termination closedness: tight σ for ±20 mm placement at trailing edge.
_PUSH_SUCCESS_STD_M = 0.015
_PUSH_WIDTH_GAP_SIGMA_M = _PUSH_SUCCESS_STD_M
# Far-field along (+Y) approach to trailing face (per-jaw, one-sided).
_PUSH_ALONG_APPROACH_STD_M = 0.050
# Overshoot decay past trailing face — pads into PCB / over top lose credit (~8 mm scale).
_PUSH_OVERSHOOT_STD_M = 0.008
_PUSH_OVERSHOOT_TARGET_ALONG_M = 0.0
# Mid-thickness height: pull pads off the PCB top face toward the trailing-edge centre plane.
_PUSH_MID_THICKNESS_STD_M = 0.012
# Z-only mid-thickness shaping is gated until coarse trailing-edge proximity is achieved.
_PUSH_MID_THICKNESS_MIN_CLOSEDNESS = 0.3
# Penalize large arm joint drift from home (discourages floor collapse before reach).
_ARM_HOME_DEVIATION_STD_RAD = 0.40
_ARM_HOME_JOINT_POS = {k: v for k, v in _ROBOT_HOME_JOINT_POS.items() if k.startswith("joint_")}
_PUSH_JAW_SPAN_SIGMA_M = 0.004
_PUSH_OPEN_TOLERANCE_M = 0.003
_PUSH_GAP_TOLERANCE_M = 0.005
# Pre-deep shaping active while both jaws are behind the trailing face (before deep along).
_PUSH_PREDEEP_ALONG_GATE_M = 0.0
# Symmetric approach — midpoint stays on trailing-edge centreline.
_PUSH_MIDPOINT_JAW_OFFSET_M = 0.0
# Wrist→jaw pitch (slide-axis elevation) for camera / structure clearance during later slide.
_PUSH_WRIST_TARGET_PITCH_DEG = 20.0
_PUSH_WRIST_PITCH_SIGMA_DEG = 5.0
# Success: mean per-jaw ``1 - tanh(dist/std)`` must reach this closedness (in [0, 1]).
_PUSH_SUCCESS_CLOSEDNESS_THRESHOLD = 0.4

# Shared geometry kwargs for straddle checks and phase transitions.
_PUSH_CHECK_KWARGS = {
    "gate_dist_m": 0.080,
    "min_along_m": 0.0,
    "width_weight": _SHORT_EDGE_WIDTH_WEIGHT,
    "pcb_half_thickness_m": PCB_Z * 0.5,
    "min_straddle_sep_m": _MIN_STRADDLE_SEP_M,
}

# Pinch orientation obs — minimum finger separation for valid cosines.
_PINCH_ORIENT_MIN_SEP_M = 0.004


def _pinch_orient_obs_params(**extra) -> dict:
    """Shared kwargs for ``pinch_orientation_cos`` policy observation."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "min_finger_sep_m": _PINCH_ORIENT_MIN_SEP_M,
        "push_axis_world": PUSH_AXIS_WORLD,
        **_gripper_wrist_kwargs(),
    }
    base.update(extra)
    return base


def _push_entity_params(**extra) -> dict:
    """Common SceneEntityCfg + geometry keys for straddle reward terms."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "half_length_m": _HALF_LENGTH_M,
        **_gripper_wrist_kwargs(),
    }
    base.update(extra)
    return base


def _push_lateral_gap_params(**extra) -> dict:
    """Kwargs for explicit symmetric jaw-axis gap shaping (±20 mm at 40 mm span)."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        "half_length_m": _HALF_LENGTH_M,
        "width_gap_target_left_m": _PUSH_GAP_LEFT_M,
        "width_gap_target_right_m": _PUSH_GAP_RIGHT_M,
        "width_gap_sigma_m": _PUSH_WIDTH_GAP_SIGMA_M,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _push_gripper_debug_params(**extra) -> dict:
    """Kwargs for push debug (TensorBoard + play console)."""
    base = {
        "asset_cfg": _GRIPPER_JOINT,
        **_push_finger_target_params(),
        "closedness_threshold": _PUSH_SUCCESS_CLOSEDNESS_THRESHOLD,
        "proximity_std_m": _PUSH_PROXIMITY_STD_M,
    }
    base.update(extra)
    return base


def _push_hold_gripper_open_always_params(**extra) -> dict:
    """Kwargs for per-step open PD hold at the straddle target width."""
    base = {
        "asset_cfg": _ROBOT_ENT,
        "joint_name": "left_carriage_joint",
        "open_width_m": _PUSH_OPEN_WIDTH_M,
        "match_sim_state": False,
        "store_target": True,
    }
    base.update(extra)
    return base


def _push_finger_geometry_params(**extra) -> dict:
    """Shared finger trailing-edge geometry (no ``std`` — set per reward / success)."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        "half_length_m": _HALF_LENGTH_M,
        "finger_offset_m": _PUSH_FINGER_OFFSET_M,
        "width_gap_target_left_m": _PUSH_GAP_LEFT_M,
        "width_gap_target_right_m": _PUSH_GAP_RIGHT_M,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _push_finger_target_params(**extra) -> dict:
    """Kwargs for success / debug closedness (tight ``std``)."""
    return _push_finger_geometry_params(std=_PUSH_SUCCESS_STD_M, **extra)


def _push_finger_proximity_params(**extra) -> dict:
    """Kwargs for per-jaw ±offset trailing-edge width proximity (wide ``std``)."""
    return _push_finger_geometry_params(std=_PUSH_PROXIMITY_STD_M, **extra)


def _push_success_params(**extra) -> dict:
    """Kwargs for straddle success — finger-target closedness ≥ threshold."""
    return _push_finger_target_params(
        closedness_threshold=_PUSH_SUCCESS_CLOSEDNESS_THRESHOLD,
        **extra,
    )


def _push_mid_thickness_params(**extra) -> dict:
    """Kwargs for straddle_tip_mid_thickness_shaping — pads at edge mid-height, not PCB top."""
    return _push_finger_geometry_params(std=_PUSH_MID_THICKNESS_STD_M, **extra)


def _push_mid_thickness_gated_params(**extra) -> dict:
    """Kwargs for gated mid-thickness shaping (active after coarse trailing-edge proximity)."""
    base = _push_mid_thickness_params(
        min_closedness=_PUSH_MID_THICKNESS_MIN_CLOSEDNESS,
        closedness_std=_PUSH_PROXIMITY_STD_M,
    )
    base.update(extra)
    return base


def _push_along_approach_params(**extra) -> dict:
    """Kwargs for per-jaw trailing-face along (+Y) bounded approach shaping."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        "half_length_m": _HALF_LENGTH_M,
        "approach_std_m": _PUSH_ALONG_APPROACH_STD_M,
        "overshoot_std_m": _PUSH_OVERSHOOT_STD_M,
        "target_along_m": _PUSH_OVERSHOOT_TARGET_ALONG_M,
        "height_gate_std_m": _ALONG_HEIGHT_GATE_STD_M,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _push_joint_home_penalty_params(**extra) -> dict:
    """Kwargs for arm joint deviation penalty from reset home pose."""
    base = {
        "asset_cfg": _ROBOT_ENT,
        "joint_positions": _ARM_HOME_JOINT_POS,
        "std": _ARM_HOME_DEVIATION_STD_RAD,
    }
    base.update(extra)
    return base


def _slide_push_progress_params(**extra) -> dict:
    """Kwargs for gated per-step leading-edge +Y progress (straddle + no lift/skid)."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "half_length_m": _HALF_LENGTH_M,
        "min_straddle_quality": _PUSH_JAW_GATE_MIN,
        "proximity_sigma_m": 0.050,
        "width_sigma_m": 0.025,
        "pcb_half_thickness_m": PCB_Z * 0.5,
        "axis_world": PUSH_AXIS_WORLD,
        "max_step_m": _SLIDE_PUSH_APPROACH_MAX_STEP_M,
        "max_off_axis_speed_m_s": _SLIDE_PUSH_MAX_OFF_AXIS_SPEED_M_S,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _push_progress_params(**extra) -> dict:
    """Push: unlock +Y credit when finger-target closedness is held (proximity σ, same as shaping)."""
    base = _slide_push_progress_params(
        min_straddle_quality=0.0,
        min_closedness_for_push=_PUSH_SUCCESS_CLOSEDNESS_THRESHOLD,
        closedness_std=_PUSH_PROXIMITY_STD_M,
        finger_offset_m=_PUSH_FINGER_OFFSET_M,
    )
    base.update(extra)
    return base


def _push_velocity_params(**extra) -> dict:
    """Push +Y velocity reward (same gate as progress, no ``max_step_m``)."""
    base = _push_progress_params()
    base.pop("max_step_m", None)
    base.update(extra)
    return base


def _push_monitor_params(**extra) -> dict:
    """Kwargs for per-step push monitoring (debug step / TensorBoard), not reward terms."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "half_length_m": _HALF_LENGTH_M,
        "axis_world": PUSH_AXIS_WORLD,
        "max_step_m": _SLIDE_PUSH_APPROACH_MAX_STEP_M,
        "max_off_axis_speed_m_s": _SLIDE_PUSH_MAX_OFF_AXIS_SPEED_M_S,
        "min_straddle_quality": _PUSH_JAW_GATE_MIN,
        "proximity_sigma_m": 0.050,
        "width_sigma_m": 0.025,
        "pcb_half_thickness_m": PCB_Z * 0.5,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        "min_closedness_for_push": _PUSH_SUCCESS_CLOSEDNESS_THRESHOLD,
        "proximity_std_m": _PUSH_PROXIMITY_STD_M,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _push_debug_params(**extra) -> dict:
    """Kwargs for push push TensorBoard / play-console monitoring."""
    base = {
        **_push_gripper_debug_params(),
        **_push_monitor_params(),
    }
    base.update(extra)
    return base


def _push_gripper_debug_step_params(**extra) -> dict:
    """Kwargs for straddle play / low-``num_envs`` console debug."""
    base = {
        **_push_debug_params(),
        "print_every_control_steps": 32,
        "print_env_id": 0,
        "enable_print": False,
    }
    base.update(extra)
    return base


def _slide_success_params(**extra) -> dict:
    """Kwargs shared by slide success termination and ``slide_success_bonus`` reward."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "half_length_m": _HALF_LENGTH_M,
        "target_lead_xy_env": _SLIDE_SUCCESS_TARGET_LEAD_XY_ENV,
        "tolerance_xy_m": _SLIDE_SUCCESS_LEAD_XY_TOLERANCE_M,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        "max_gripper_gap_m": _SLIDE_MAX_GRIPPER_GAP_M,
        "require_gripper_closed": False,
        "axis_world": PUSH_AXIS_WORLD,
    }
    base.update(extra)
    return base


def _slide_straddle_hold_params(**extra) -> dict:
    """Kwargs for trailing-edge ±20 mm straddle hold during slide."""
    base = {
        "std": _SLIDE_STRADDLE_HOLD_STD_M,
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        "half_length_m": _HALF_LENGTH_M,
        "finger_offset_m": _PUSH_FINGER_OFFSET_M,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _slide_finger_sync_params(**extra) -> dict:
    """Kwargs for symmetric finger push-axis depth when yaw is aligned."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        "axis_world": PUSH_AXIS_WORLD,
        "yaw_good_cos": _SLIDE_YAW_GOOD_COS,
        "sync_std_m": _SLIDE_FINGER_Y_SYNC_STD_M,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _slide_yaw_corrective_params(**extra) -> dict:
    """Kwargs for asymmetric finger push when PCB yaw exceeds tolerance."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        "axis_world": PUSH_AXIS_WORLD,
        "yaw_bad_cos": _SLIDE_YAW_BAD_COS,
        "asym_std_m": _SLIDE_YAW_ASYM_STD_M,
        "asym_gain_m": _SLIDE_YAW_ASYM_GAIN_M,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _slide_gripper_span_params(**extra) -> dict:
    """Kwargs for nominal vs yaw-recovery gripper span shaping."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        "axis_world": PUSH_AXIS_WORLD,
        "nominal_span_m": _SLIDE_GRIPPER_NOMINAL_SPAN_M,
        "max_open_mult": _SLIDE_GRIPPER_MAX_OPEN_MULT,
        "span_sigma_m": _SLIDE_GRIPPER_SPAN_SIGMA_M,
        "yaw_bad_cos": _SLIDE_YAW_BAD_COS,
    }
    base.update(extra)
    return base


def _slide_jaw_orient_params(**extra) -> dict:
    """Kwargs for jaw rail vertical during slide."""
    base = {
        **_push_entity_params(),
        "gate_dist_m": 0.12,
        "min_finger_sep_m": _MIN_STRADDLE_SEP_M,
        "width_weight": _SHORT_EDGE_WIDTH_WEIGHT,
    }
    base.update(extra)
    return base


def _slide_wrist_align_params(**extra) -> dict:
    """Kwargs for wrist→carriage push-axis alignment during slide."""
    base = {
        **_push_entity_params(),
        "gate_dist_m": 0.12,
        "min_finger_sep_m": _MIN_STRADDLE_SEP_M,
        "width_weight": _SHORT_EDGE_WIDTH_WEIGHT,
        "push_axis_world": PUSH_AXIS_WORLD,
        "yaw_only": True,
    }
    base.update(extra)
    return base


def _push_termination_params(**extra) -> dict:
    """Entity + geometry kwargs shared by straddle-success termination and bonus."""
    return _push_success_params(**extra)


@configclass
class WidowXPcbSceneCfg(InteractiveSceneCfg):
    """Scene assets for the WidowX PCB task.

    Contains ground, light, robot, PCB cuboid, and the static magazine + conveyor USD (single asset).
    """
    ground = AssetBaseCfg(prim_path="/World/defaultGroundPlane", spawn=sim_utils.GroundPlaneCfg())
    
    light = AssetBaseCfg(prim_path="/World/defaultLight", spawn=sim_utils.DistantLightCfg(intensity=3000.0))
    
    robot = ArticulationCfg(
        prim_path="{ENV_REGEX_NS}/Robot",
        spawn=sim_utils.UsdFileCfg(
            # Trossen AI WidowX Follower USD (stiffness/damping already baked in).
            usd_path=os.path.join(ASSET_DIR, "usd_model", "usd_robot", "wxai", "wxai_follower.usd"),
            rigid_props=sim_utils.RigidBodyPropertiesCfg(
                disable_gravity=False,
                max_depenetration_velocity=_ROBOT_MAX_DEPENETRATION_VELOCITY,
            ),
            collision_props=sim_utils.CollisionPropertiesCfg(
                contact_offset=_PCB_CONTACT_OFFSET_M,
                rest_offset=0.0,
            ),
            articulation_props=sim_utils.ArticulationRootPropertiesCfg(
                enabled_self_collisions=True,
                solver_position_iteration_count=32,
                solver_velocity_iteration_count=16,
            ),
        ),
        init_state=ArticulationCfg.InitialStateCfg(
            pos=_ROBOT_BASE_POS,
            rot=_ROBOT_BASE_ROT_WXYZ,
            joint_pos=_ROBOT_HOME_JOINT_POS,
        ),
        # Arm: stiffness=0 — task-space OSC torques via ``WidowXTaskSpaceImpedanceAction``.
        actuators={
            "wxai_arm": ImplicitActuatorCfg(
                joint_names_expr=["joint_[0-5]"],
                stiffness=0.0,
                damping=1.0,   # low; primary damping from VIC ζ in the action term
            ),
            # right_carriage_joint is a mimic joint in the USD (driven by left_carriage_joint).
            "wxai_gripper": ImplicitActuatorCfg(
                joint_names_expr=["left_carriage_joint"],
                # PD holds carriage closed; policy effort adds on top during Grasp/Slide phases.
                stiffness=_GRIPPER_ACTUATOR_STIFFNESS,
                damping=_GRIPPER_ACTUATOR_DAMPING,
            ),
        },
        soft_joint_pos_limit_factor=1.0,
    )
    
    pcb = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/PCB",
        spawn=sim_utils.CuboidCfg(
            size=(PCB_X, PCB_Y, PCB_Z),
            rigid_props=sim_utils.RigidBodyPropertiesCfg(
                solver_position_iteration_count=_PCB_SOLVER_POS_ITERATIONS,
                solver_velocity_iteration_count=_PCB_SOLVER_VEL_ITERATIONS,
                max_depenetration_velocity=_PCB_MAX_DEPENETRATION_VELOCITY,
                max_linear_velocity=2.0,
                max_angular_velocity=90.0,
                linear_damping=_PCB_LINEAR_DAMPING,
                angular_damping=_PCB_ANGULAR_DAMPING,
            ),
            collision_props=sim_utils.CollisionPropertiesCfg(
                contact_offset=_PCB_CONTACT_OFFSET_M,
                rest_offset=_PCB_REST_OFFSET_M,
            ),
            physics_material=sim_utils.RigidBodyMaterialCfg(
                friction_combine_mode="multiply",
                restitution_combine_mode="multiply",
                static_friction=_PCB_STATIC_FRICTION,
                dynamic_friction=_PCB_DYNAMIC_FRICTION,
                restitution=0.0,
            ),
            mass_props=sim_utils.MassPropertiesCfg(mass=PCB_MASS_KG),
            visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.1, 0.4, 0.1)),
        ),
        # Flat on conveyor; front edge 20 mm before slot (see ``_PCB_INIT_POS``).
        init_state=RigidObjectCfg.InitialStateCfg(pos=_PCB_INIT_POS, rot=_PCB_INIT_ROT_WXYZ),
    )


    pcb_insertion_env = AssetBaseCfg(
        prim_path="{ENV_REGEX_NS}/Magazine",
        spawn=sim_utils.UsdFileCfg(
            # Generated by usd_model/env_v6/convert_to_usd.py from assembly_6.urdf.
            # Materials: SteelMaterial / BeltMaterial / RailMaterial / StandMaterial.
            # Colliders: magazine + rails + belts = triangle mesh (none); stand = convexDecomposition.
            # Gripper (carriage) friction set via _GRIPPER_FINGER_STATIC_FRICTION event in env_cfg.
            usd_path=os.path.join(ASSET_DIR, "usd_model", "env_v6", "pcb_insertion_env.usd"),

        ), 
        # Fixture pose: _MAG_POS = assembly root in world; -90 deg Z rotation (see FK comments above).
        init_state=AssetBaseCfg.InitialStateCfg(
            pos=_MAG_POS,
            rot=_MAG_ROT_WXYZ,
        ),
    )

@configclass
class ActionsCfgPush:
    """Push: task-space OSC (Δpose, K, ζ); gripper PD-held open at 30 mm."""

    arm_action = WidowXTaskSpaceImpedanceActionCfg(
        asset_name="robot",
        joint_names=["joint_[0-5]"],
        body_name=_EE_OSC_BODY_NAME,
        body_offset=WidowXTaskSpaceImpedanceActionCfg.OffsetCfg(
            # Distal offset wrist→jaw pad midpoint (approx.; tune in Sim vs ``_GRIPPER_TIP_OFFSET_M``).
            pos=(0.0, 0.0, _GRIPPER_TIP_OFFSET_M),
            rot=(1.0, 0.0, 0.0, 0.0),
        ),
        position_scale=_ARM_TASK_POSITION_SCALE,
        orientation_scale=_ARM_TASK_ORIENTATION_SCALE,
        stiffness_scale=1.0,
        damping_ratio_scale=1.0,
        controller_cfg=OperationalSpaceControllerCfg(
            target_types=["pose_rel"],
            impedance_mode="variable",
            motion_control_axes_task=_ARM_TASK_MOTION_AXES,
            motion_stiffness_task=_ARM_TASK_DEFAULT_STIFFNESS,
            motion_damping_ratio_task=_ARM_TASK_DEFAULT_DAMPING_RATIO,
            motion_stiffness_limits_task=_ARM_TASK_STIFFNESS_LIMITS,
            motion_damping_ratio_limits_task=_ARM_TASK_DAMPING_RATIO_LIMITS,
            gravity_compensation=True,
            inertial_dynamics_decoupling=False,
            nullspace_control="none",
        ),
    )


@configclass
class ObservationsCfg:
    """Observation groups exposed to the policy."""

    @configclass
    class PolicyCfg(ObservationGroupCfg):
        """Per-step policy observations: robot joints, PCB pose, EE (grip midpoint)."""
        joint_pos = ObservationTermCfg(func=mdp.joint_pos_rel)
        joint_vel = ObservationTermCfg(func=mdp.joint_vel_rel)

        object_pos = ObservationTermCfg(
            func=pcb_trailing_short_edge_center_env,
            params={"pcb_cfg": _PCB_ENT, "half_length_m": _HALF_LENGTH_M},
        )

        # EE: midpoint of contact pad tips (carriage-adjusted; matches finger_proximity reward).
        ee_pos = ObservationTermCfg(
            func=gripper_jaw_pad_midpoint_position_env,
            params={
                "left_finger_cfg": _LEFT_FINGER,
                "right_finger_cfg": _RIGHT_FINGER,
                "gripper_joint_cfg": _GRIPPER_JOINT,
                **_gripper_kinematics_kwargs(),
            },
        )
        # 0 = closed, 1 = open — normalized by straddle target width (40 mm).
        gripper_opening = ObservationTermCfg(
            func=gripper_opening_normalized,
            params={
                "asset_cfg": SceneEntityCfg("robot", joint_names=["left_carriage_joint"]),
                "open_width_m": _PUSH_OPEN_WIDTH_M,
            },
        )
        # Jaw mid vs PCB center along thickness (pinch alignment); helps learn close from top/bottom.
        ee_thickness_offset = ObservationTermCfg(
            func=gripper_mid_thickness_offset_obs,
            params={
                "pcb_cfg": SceneEntityCfg("pcb"),
                "left_finger_cfg": _LEFT_FINGER,
                "right_finger_cfg": _RIGHT_FINGER,
                "scale_m": 0.012,
                "gripper_joint_cfg": _GRIPPER_JOINT,
                **_gripper_kinematics_kwargs(),
            },
        )
        # Jaw rail ∥ world +Z; wrist→carriage line ∥ push axis (+Y).
        pinch_orientation_cos = ObservationTermCfg(
            func=gripper_pinch_orientation_cos_obs,
            params=_pinch_orient_obs_params(),
        )
        # Jaw mid vs trailing short-edge centre in PCB frame (along / width / thick).
        trailing_edge_error = ObservationTermCfg(
            func=gripper_trailing_edge_error_obs,
            params={
                **_push_entity_params(
                    gripper_joint_cfg=_GRIPPER_JOINT,
                    scale_along_m=_HALF_LENGTH_M,
                    scale_width_m=_PCB_HALF_WIDTH_M,
                    scale_thick_m=0.050,
                    **_gripper_kinematics_kwargs(),
                ),
            },
        )
        # Task-space OSC: commanded stiffness K and damping ratio ζ (normalized [-1, 1] per task axis).
        vic_stiffness = ObservationTermCfg(
            func=vic_arm_stiffness_normalized_obs,
            params={"action_name": "arm_action"},
        )
        vic_damping = ObservationTermCfg(
            func=vic_arm_damping_normalized_obs,
            params={"action_name": "arm_action"},
        )

        pcb_yaw_sin = ObservationTermCfg(
            func=slide_pcb_yaw_sin_obs,
            params={"pcb_cfg": _PCB_ENT, "axis_world": PUSH_AXIS_WORLD},
        )
        finger_push_axis_delta = ObservationTermCfg(
            func=slide_finger_push_axis_delta_obs,
            params={
                "left_finger_cfg": _LEFT_FINGER,
                "right_finger_cfg": _RIGHT_FINGER,
                "gripper_joint_cfg": _GRIPPER_JOINT,
                "axis_world": PUSH_AXIS_WORLD,
                **_gripper_kinematics_kwargs(),
            },
        )

        # # Sim-to-real: applied joint torque (N·m) and stall proxy for jamming/back-off.
        # joint_torque = ObservationTermCfg(
        #     func=arm_joint_torque_normalized_obs,
        #     params={
        #         "asset_cfg": _ARM_JOINT_OBS_ENT,
        #         "torque_scale_nm": _ARM_TORQUE_OBS_SCALE_NM,
        #     },
        # )
        # joint_stall = ObservationTermCfg(
        #     func=arm_joint_stall_obs,
        #     params={
        #         "asset_cfg": _ARM_JOINT_OBS_ENT,
        #         "torque_scale_nm": _ARM_TORQUE_OBS_SCALE_NM,
        #         "vel_eps_rad_s": _ARM_STALL_VEL_EPS_RAD_S,
        #     },
        # )
    policy: PolicyCfg = PolicyCfg()


@configclass
class ObservationsCfgSlide:
    """Slide-phase observations: goal is the slot mouth (leading-edge approach target)."""

    @configclass
    class PolicyCfg(ObservationGroupCfg):
        joint_pos = ObservationTermCfg(
            func=joint_pos_rel_episode_reset,
            params={"asset_cfg": _ROBOT_ENT},
        )
        joint_vel = ObservationTermCfg(
            func=mdp.joint_vel_rel,
            clip=(-20.0, 20.0),
        )
        object_pos = ObservationTermCfg(
            func=pcb_leading_short_edge_center_env,
            params={"pcb_cfg": _PCB_ENT, "half_length_m": _HALF_LENGTH_M},
        )
        ee_pos = ObservationTermCfg(
            func=gripper_midpoint_position_env,
            params={
                "left_finger_cfg": SceneEntityCfg("robot", body_names="gripper_left"),
                "right_finger_cfg": SceneEntityCfg("robot", body_names="gripper_right"),
            },
        )
        # Jaw rail ∥ world +Z; wrist→carriage +Y heading in XY (yaw only — pitch in Z allowed).
        pinch_orientation_cos = ObservationTermCfg(
            func=gripper_pinch_orientation_cos_obs,
            params=_pinch_orient_obs_params(yaw_only_wrist_align=True),
        )
        gripper_opening = ObservationTermCfg(
            func=gripper_opening_normalized,
            params={
                "asset_cfg": SceneEntityCfg("robot", joint_names=["left_carriage_joint"]),
                "open_width_m": _PUSH_OPEN_WIDTH_M,
            },
        )
        pcb_to_slot_error = ObservationTermCfg(
            func=pcb_to_target_error_obs,
            params={
                "pcb_cfg": _PCB_ENT,
                "target_xyz_env": _SLIDE_GOAL_LEAD_XYZ_ENV,
                "scale_xyz_m": (0.05, 0.25, 0.05),
                "half_length_m": _HALF_LENGTH_M,
            },
        )
        pcb_orientation = ObservationTermCfg(
            func=pcb_insertion_orientation_obs,
            params={
                "pcb_cfg": _PCB_ENT,
                "align_axis_world": PUSH_AXIS_WORLD,
            },
        )
        pcb_yaw_sin = ObservationTermCfg(
            func=slide_pcb_yaw_sin_obs,
            params={"pcb_cfg": _PCB_ENT, "axis_world": PUSH_AXIS_WORLD},
        )
        finger_push_axis_delta = ObservationTermCfg(
            func=slide_finger_push_axis_delta_obs,
            params={
                "left_finger_cfg": _LEFT_FINGER,
                "right_finger_cfg": _RIGHT_FINGER,
                "gripper_joint_cfg": _GRIPPER_JOINT,
                "axis_world": PUSH_AXIS_WORLD,
                **_gripper_kinematics_kwargs(),
            },
        )

    policy: PolicyCfg = PolicyCfg()


@configclass
class RewardsPushCfg():
    """Push reward stack — open symmetric width-axis trailing-edge straddle (no pinch).

    1. APPROACH  — bounded trailing-face advance + overshoot decay + mid-thickness + width proximity.
    2. SUCCESS   — finger-target closedness ≥ 0.5 (tight σ).
    """

    action_rate_penalty = RewardTermCfg(func=action_rate_l2, weight=-0.02)

    # # Far-field +Y approach to trailing face (both jaws must advance together).
    # trailing_face_approach = RewardTermCfg(
    #     func=straddle_trailing_face_bounded_approach_reward,
    #     params=_push_along_approach_params(),
    #     weight=200.0,
    # )

    # Pull pads to PCB mid-thickness — only after coarse trailing-edge proximity.
    tip_mid_thickness = RewardTermCfg(
        func=straddle_tip_mid_thickness_shaping_gated,
        params=_push_mid_thickness_gated_params(),
        weight=80.0,
    )
    
    # Per-jaw ±15 mm targets on trailing face at mid-height (wide proximity σ = 10 cm).
    finger_proximity = RewardTermCfg(
        func=straddle_finger_trailing_width_proximity,
        params=_push_finger_proximity_params(),
        weight=150.0,
    )


    # Explicit symmetric jaw-axis gap shaping (±15 mm at 40 mm span).
    lateral_gap = RewardTermCfg(
        func=straddle_lateral_gap_shaping,
        params=_push_lateral_gap_params(),
        weight=10.0,
    )

    # straddle_success_bonus = RewardTermCfg(
    #     func=straddle_success_bonus_reward,
    #     params=_push_termination_params(),
    #     weight=1000.0,
    # )

    # Continuous flatness shaping — discourages knock-over before hard tilt terminations fire.
    # pcb_tilt_penalty = RewardTermCfg(
    #     func=pcb_thickness_axis_tilt_penalty,
    #     params={"pcb_cfg": _PCB_ENT},
    #     weight=-100.0,
    # )

    # ========================== Slide Rewards ==========================

    leading_edge_push_progress = RewardTermCfg(
        func=pcb_leading_edge_push_axis_approach_progress_gated,
        params=_push_progress_params(),
        weight=400.0,
    )
    push_axis_velocity = RewardTermCfg(
        func=pcb_push_axis_velocity_reward_gated,
        params=_push_velocity_params(min_push_speed_m_s=0.001),
        weight=400.0,
    )
    slide_travel_milestone = RewardTermCfg(
        func=slide_leading_edge_travel_milestone_bonus,
        params={
            "pcb_cfg": _PCB_ENT,
            "half_length_m": _HALF_LENGTH_M,
            "target_lead_y_env": _SLIDE_SUCCESS_LEAD_Y_ENV,
            "milestone_fractions": _SLIDE_TRAVEL_MILESTONE_FRACTIONS,
            "axis_world": PUSH_AXIS_WORLD,
            "max_lead_x_drift_m": _SLIDE_MILESTONE_MAX_LEAD_X_DRIFT_M,
            "belt_center_z_env": _SLIDE_BELT_CENTER_Z_ENV,
            "max_lead_z_drift_m": _SLIDE_MILESTONE_MAX_LEAD_Z_DRIFT_M,
        },
        weight=300.0,
    )

    goal_lead_proximity = RewardTermCfg(
        func=pcb_leading_edge_insertion_proximity_reward,
        params={
            "pcb_cfg": _PCB_ENT,
            "half_length_m": _HALF_LENGTH_M,
            "target_lead_xyz_env": _SLIDE_GOAL_LEAD_XYZ_ENV,
            "sigma_m": 0.12,
        },
        weight=100.0,
    )

    pcb_yaw_alignment = RewardTermCfg(
        func=slide_pcb_yaw_xy_alignment_shaping,
        params={"pcb_cfg": _PCB_ENT, "axis_world": PUSH_AXIS_WORLD},
        weight=100.0,
    )
    # yaw_corrective_push = RewardTermCfg(
    #     func=slide_yaw_corrective_asymmetric_push_shaping,
    #     params=_slide_yaw_corrective_params(),
    #     weight=45.0,
    # )
    # gripper_span_yaw_recovery = RewardTermCfg(
    #     func=slide_gripper_span_yaw_recovery_shaping,
    #     params=_slide_gripper_span_params(),
    #     weight=30.0,
    # )

    slide_success_bonus = RewardTermCfg(
        func=slide_success_bonus_reward,
        params=_slide_success_params(),
        weight=10000.0,
    )

    # After all reward terms (especially ``leading_edge_push_progress``) so debug does not
    # consume ``_INSERT_PREV_LEAD_PROJ`` before the gated progress reward runs.
    push_gripper_debug_monitor = RewardTermCfg(
        func=push_gripper_debug_monitor_reward,
        params=_push_debug_params(),
        weight=1e-10,
    )


@configclass
class EventCfgPush:
    """Phase 1 reset: randomized PCB pose on conveyor, gripper held open, arm at fixed home."""

    reset_pcb_on_conveyor = EventTermCfg(
        func=reset_pcb_on_guide_rails_randomized,
        mode="reset",
        params={
            "pcb_cfg": _PCB_ENT,
            "pos_env_local": _PCB_INIT_POS,
            "rot_wxyz": _PCB_INIT_ROT_WXYZ,
            "pos_offset_ranges": _PCB_POS_OFFSET_RANGES,
            "yaw_offset_range": _PCB_YAW_OFFSET_RANGE,
            "velocity_scale": 0.0,
            "half_length_m": _HALF_LENGTH_M,
            "slot_mouth_y_env": _MAG_Y_NEAR_FACE_ENV,
        },
    )
    reset_robot_home = EventTermCfg(
        func=reset_robot_joints_to_values,
        mode="reset",
        params={
            "asset_cfg": _ROBOT_ENT,
            "joint_positions": _ROBOT_HOME_JOINT_POS,
            "velocity_scale": 0.0,
        },
    )
    # Gripper implicit PD default target is 0 (closed).  Command 40 mm open and cache target.
    hold_gripper_on_reset = EventTermCfg(
        func=hold_gripper_open,
        mode="reset",
        params=_push_hold_gripper_open_always_params(),
    )
    # Re-apply open PD every step so arm torques cannot collapse the carriage.
    hold_gripper_every_step = EventTermCfg(
        func=hold_gripper_open,
        mode="interval",
        is_global_time=True,
        interval_range_s=(0.0, 0.0),
        params={
            **_push_hold_gripper_open_always_params(),
            "store_target": False,
        },
    )
    # # Play-only console print (accumulation via ``push_gripper_debug_monitor`` reward term).
    # push_gripper_debug_print = EventTermCfg(
    #     func=push_gripper_debug_step,
    #     mode="interval",
    #     is_global_time=True,
    #     interval_range_s=(0.0, 0.0),
    #     params={**_push_gripper_debug_step_params(), "accumulate": False},
    # )


@configclass
class CurriculumPushDebugCfg:
    """Episode push debug scalars → TensorBoard ``Curriculum/push_gripper_debug/*``."""

    push_gripper_debug = CurriculumTermCfg(
        func=push_gripper_debug_curriculum,
        params=_push_debug_params(),
    )


@configclass
class TerminationsSharedCfg:
    """Safety terminations shared by all variants."""

    time_out = TerminationTermCfg(func=mdp.time_out, time_out=True)
    

@configclass
class TerminationsPushCfg(TerminationsSharedCfg):
    """Push PCB safety failures (tilt / long-axis) and slide success termination."""

    pcb_tilt_excessive = TerminationTermCfg(
        func=pcb_tilt_beyond_limit,
        params={"pcb_cfg": _PCB_ENT, "max_tilt_penalty": _PUSH_MAX_TILT_PENALTY},
    )
    pcb_long_axis_not_horizontal = TerminationTermCfg(
        func=pcb_long_axis_vertical_component_exceeds,
        params={"pcb_cfg": _PCB_ENT, "max_abs_z": _PUSH_MAX_LONG_AXIS_ABS_Z},
    )
    pcb_fallen_below_rail = TerminationTermCfg(
        func=pcb_root_height_below_env_minimum,
        params={"pcb_cfg": _PCB_ENT, "min_height_env": _PCB_TERMINATE_MIN_HEIGHT_ENV},
    )
    pcb_moving_backward = TerminationTermCfg(
        func=pcb_moving_backward_termination,
        params={"pcb_cfg": _PCB_ENT, "backward_vel_threshold": -0.03, "min_steps": 4},
    )
    # Same leading-edge XYZ box as ``slide_success_bonus`` (see ``_slide_success_params``).
    slide_success = TerminationTermCfg(
        func=slide_success,
        params=_slide_success_params(),
    )


@configclass
class _WidowXPcbEnvCfgBase(ManagerBasedRLEnvCfg):
    """Shared scene, actions, observations, and simulation for all task variants."""

    scene: WidowXPcbSceneCfg = WidowXPcbSceneCfg(num_envs=2048, env_spacing=1.5)
    observations: ObservationsCfg = ObservationsCfg()
    # actions: ActionsCfg = ActionsCfg()
    sim: sim_utils.SimulationCfg = sim_utils.SimulationCfg(
        dt=0.002,
        render_interval=1,
        physics_material=sim_utils.RigidBodyMaterialCfg(
            friction_combine_mode="multiply",
            restitution_combine_mode="multiply",
            static_friction=_SIM_DEFAULT_STATIC_FRICTION,
            dynamic_friction=_SIM_DEFAULT_DYNAMIC_FRICTION,
            restitution=0.0,
        ),
        physx=sim_utils.PhysxCfg(
            # CCD prevents fast-moving thin objects from tunneling through meshes.
            enable_ccd=True,
            # Solve articulation contacts after rigid-rigid so the gripper
            # joints feel the PCB contact force before clamping further.
            solve_articulation_contact_last=True,
            # Stabilization pass: adds a damping term to contacts that are
            # nearly-resolved, preventing the PCB from jittering on the
            # conveyor or inside the gripper.
            enable_stabilization=True,
            min_position_iteration_count=_SIM_MIN_POS_ITERATIONS,
            min_velocity_iteration_count=_SIM_MIN_VEL_ITERATIONS,
            # Larger GPU buffers for triangle-mesh fixture colliders (rails/belts/magazine)
            # and many parallel envs. Overflow drops contacts (PCB tunnels / floats).
            gpu_max_rigid_contact_count=2**23,
            gpu_max_rigid_patch_count=2**20,
            gpu_collision_stack_size=2**29,  # ~512 MB; log asked for ~443 MB at 4096 envs
        ),
    )

    def __post_init__(self):
        self.viewer.eye = (0.95, 0.95, 0.65)
        self.viewer.lookat = (0.25, 0.35, 0.08)
        self.decimation = 4
        self.sim.render_interval = self.decimation


@configclass
class WidowXPcbPushEnvCfg(_WidowXPcbEnvCfgBase):
    """Open-jaw trailing-edge approach and +Y push into the magazine slot."""

    actions: ActionsCfgPush = ActionsCfgPush()
    rewards: RewardsPushCfg = RewardsPushCfg()
    events: EventCfgPush = EventCfgPush()
    terminations: TerminationsPushCfg = TerminationsPushCfg()
    curriculum: CurriculumPushDebugCfg = CurriculumPushDebugCfg()

    def __post_init__(self):
        super().__post_init__()
        self.episode_length_s = 4.0
