from __future__ import annotations

"""Environment configuration for WidowX PCB slot insertion.

Two-phase task design:
  Phase 1 (Grasp):  approach + pinch the trailing short-edge **centre**.
  Phase 2 (Insert): slide the grasped PCB along world +Y into the magazine slot.

Registered variants (see ``__init__.py``):
  - ``Isaac-WidowX-PCB-Grasp-v0``  — phase 1 only (train grasp first)
  - ``Isaac-WidowX-PCB-Insert-v0`` — phase 2 only (reset with PCB snapped to closed jaws)
"""

import os
from isaaclab.utils import configclass
from isaaclab.envs import ManagerBasedRLEnvCfg
from isaaclab.assets import ArticulationCfg, AssetBaseCfg, RigidObjectCfg
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.managers import (
    EventTermCfg,
    ObservationGroupCfg,
    ObservationTermCfg,
    RewardTermCfg,
    SceneEntityCfg,
    TerminationTermCfg,
)
from isaaclab.actuators import ImplicitActuatorCfg
import isaaclab.sim as sim_utils
import isaaclab.envs.mdp as mdp
from .mdp_custom import (
    gripper_midpoint_position_env,
    gripper_opening_normalized,
    pcb_long_axis_parallel_to_push_reward,
    pcb_leading_edge_insertion_proximity_reward,
    pcb_lin_vel_y_toward_lead_target_y,
    pcb_horizontal_velocity_perpendicular_to_axis_penalty,
    action_rate_l2,
    pcb_height_below_reference,
    pcb_push_axis_displacement_penalty,
    pcb_thickness_axis_tilt_penalty,
    # --- grasp / push rewards ---
    grasp_success_bonus_reward,
    gripper_jaw_rail_vertical_shaping,
    gripper_wrist_carriage_push_axis_shaping,
    gripper_jaw_rail_horizontal_penalty,
    pcb_between_gripper_fingers,
    pcb_finger_object_proximity,
    gripper_closing_reward,
    premature_close_penalty,
    pcb_insertion_depth_reward,
    grasp_edge_center_achieved,
    # --- resets & terminations ---
    reset_pcb_on_guide_rails,
    reset_robot_joints_to_values,
    snap_pcb_root_to_short_edge_grasp,
    pcb_dropped_from_gripper,
    pcb_root_height_below_env_minimum,
    pcb_tilt_beyond_limit,
    pcb_long_axis_vertical_component_exceeds,
    pcb_tilt_before_grasp_termination,
    pcb_xy_plane_rotation_before_grasp_termination,
    gripper_mid_thickness_offset_obs,
    gripper_trailing_edge_error_obs,
    gripper_pinch_orientation_cos_obs,
    pcb_moving_backward_termination,
)

# Conversion: mm to meters
PCB_X = 240.0 * 0.001
PCB_Y = 77.5 * 0.001
PCB_Z = 0.0005
_PCB_HALF_WIDTH_M = PCB_Y * 0.5
_SHORT_EDGE_WIDTH_WEIGHT = 3.0
ASSET_DIR = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Assembly (magazine + stand + conveyor) placement  — env_v3 / assembly_2
# ---------------------------------------------------------------------------
# pcb_insertion_env.usd is generated by usd_model/env_v3/convert_to_usd.py.
# Short axle rods (Part_1_4.stl ~120 mm) + width cross-rods omitted; guide rails kept.
# All mesh vertices are FK-baked into the URDF "root" frame at q=0.
#
# Rotation: -90 deg about world Z (quaternion w=0.707, z=-0.707).
#   root +Y  →  world +X
#   root -X  →  world +Y   (push direction)
#   root +Z  →  world +Z
#
# env_v3 FK key positions in root frame (from convert_to_usd.py):
#   chip visual centre : root ( 0.074,  0.430, -0.116)
#   assembly bounding box root X: [-0.396,  0.316]
#   assembly bounding box root Z: [-0.277, -0.097]
#
# With _MAG_POS=(tx, ty, tz) world coordinates are:
#   world_x = root_Y + tx,   world_y = -root_X + ty,   world_z = root_Z + tz
#
# Chosen _MAG_POS = (-0.380, 0.094, 0.280):
#   chip (conveyor) world   : ( 0.050,  0.020,  0.164) m
#   slot entrance world Y   :  0.490 m  (assembly root X-min)
#
# TUNE _MAG_POS and _CONVEYOR_SURFACE_Z in Isaac Sim after loading.
_MAG_POS      = (-0.380, 0.094, 0.350)
_MAG_ROT_WXYZ = (0.7071068, 0.0, 0.0, -0.7071068)   # -90 deg about world Z

# World-frame push direction: root -X  →  world +Y.
PUSH_AXIS_WORLD = (0.0, 1.0, 0.0)

# ---------------------------------------------------------------------------
# Robot — independent of PCB / slot geometry (tune in Isaac Sim)
# ---------------------------------------------------------------------------
# Base beside the conveyor; +90° CCW yaw about world +Z (``_ROBOT_BASE_ROT_WXYZ``).
_ROBOT_BASE_POS = (0.05, -0.35, 0.00)
# +90° CCW about world +Z (w, x, y, z).
_ROBOT_BASE_ROT_WXYZ = (0.7071068, 0.0, 0.0, 0.7071068)

_ROBOT_HOME_JOINT_POS = {
    "joint_0": 0.0,    # base yaw — nearly 0 (PCB is almost directly in +X from base)
    "joint_1": 0.0,    # shoulder pitch down — smaller than 1.2 to reach forward/up
    "joint_2": 0.3,    # elbow bend / 1.2
    "joint_3": 0.0,    # wrist pitch
    "joint_4": 0.0,  # wrist roll ≈ −90° — jaw rail vertical (⊥ XY), not level carriage
    "joint_5": 1.5,    # wrist yaw — face toward conveyor (+Y approach)
    "left_carriage_joint": 0.020,  # open
}
# Insert-phase reset: same arm pose but closed gripper; PCB is snapped to the jaws afterward.
_INSERT_INIT_JOINT_POS = {**_ROBOT_HOME_JOINT_POS, "left_carriage_joint": PCB_Z * 0.5}
# Must match the joint value when the gripper is fully open (same as left_carriage_joint above).
_GRIPPER_OPEN_WIDTH_M = 0.020

# ---------------------------------------------------------------------------
# Conveyor + slot — independent of robot (env_v3 FK at _MAG_POS above)
# ---------------------------------------------------------------------------
_SLOT_MOUTH_Y_ENV = 0.490          # slot entrance Y (assembly root X-min → world +Y)
_CONVEYOR_CENTER_X_ENV = 0.050     # chip / conveyor centre X in env frame
_CONVEYOR_SURFACE_Z = 0.163        # conveyor top Z (chip FK z + _MAG_POS[2] − PCB_Z/2)
_PCB_CENTER_Z_ENV = _CONVEYOR_SURFACE_Z + PCB_Z * 0.5 +0.07

# ---------------------------------------------------------------------------
# PCB — derived only from conveyor + slot (not from robot / gripper)
# ---------------------------------------------------------------------------
_PCB_FRONT_EDGE_GAP_M = 0.020      # front edge (toward +Y) this far before slot mouth
_PCB_INIT_Y_OFFSET_M = -0.1

# body +X (long) || world +Y; centre on conveyor, bottom on belt top
_PCB_INIT_POS = (
    _CONVEYOR_CENTER_X_ENV,
    _SLOT_MOUTH_Y_ENV - _PCB_FRONT_EDGE_GAP_M - PCB_X * 1.5 + _PCB_INIT_Y_OFFSET_M,
    _PCB_CENTER_Z_ENV,
)
_PCB_INIT_ROT_WXYZ = (0.7071068, 0.0, 0.0, 0.7071068)

_MIN_PCB_HEIGHT_ENV = _CONVEYOR_SURFACE_Z - 0.005
_PCB_TERMINATE_MIN_HEIGHT_ENV = _CONVEYOR_SURFACE_Z - 0.025
# Grasp phase: penalize sliding the board toward the slot (+Y) beyond this displacement.
_PCB_MAX_PUSH_DISPLACEMENT_M = 0.020

_SLOT_MOUTH_LEAD_TARGET_XYZ_ENV = (
    _CONVEYOR_CENTER_X_ENV,
    _SLOT_MOUTH_Y_ENV,
    _PCB_CENTER_Z_ENV,
)

# Shared SceneEntityCfg snippets (reward / event params).
_PCB_ENT = SceneEntityCfg("pcb")
_ROBOT_ENT = SceneEntityCfg("robot")
_LEFT_FINGER = SceneEntityCfg("robot", body_names="gripper_left")
_RIGHT_FINGER = SceneEntityCfg("robot", body_names="gripper_right")
_GRIPPER_JOINT = SceneEntityCfg("robot", joint_names=["left_carriage_joint"])
# wxai ``gripper_left``/``gripper_right`` body origins sit on the carriage; pad tips are ~6 cm distally.
_GRIPPER_TIP_OFFSET_M = 0.00
_WRIST_BODY = SceneEntityCfg("robot", body_names="link_6")
_HALF_LENGTH_M = PCB_X * 0.5


def _gripper_kinematics_kwargs() -> dict:
    """Pad-tip offset applied to all grasp geometry (rewards, obs, success, snap)."""
    return {
        "tip_offset_m": _GRIPPER_TIP_OFFSET_M,
        "wrist_body_cfg": _WRIST_BODY,
    }

# Relaxed straddle threshold for early learning (≈35% of board thickness between jaw tips).
_MIN_STRADDLE_SEP_M = PCB_Z * 0.20

# Grasp-success check kwargs reused by phase transition, bonus, and termination.
# Thresholds are intentionally generous: the policy must achieve a real closed straddle
# on the trailing edge, but sim contact/damping and PCB thickness limit how far the
# carriage can physically close.
#
# ``closed_threshold``: gq < threshold * open_width.  PCB is 2.5 mm thick, one jaw travels
#   half that = 1.25 mm from centre, so carriage closes to ~1.25 mm.  With open_width=10 mm,
#   threshold = 0.75 means gq < 7.5 mm → generous, fires once gripper starts to bite.
#   Use 0.60 (< 6 mm) as a stricter but still reachable target.
# ``width_frac``: each jaw Y-error < half_width * frac.  half_width = 38.75 mm.
#   0.15 → < 5.8 mm lateral offset; enough to reward centring without being unreachable.
# ``gate_dist_m``: jaw-mid distance to trailing edge < this.  20 mm is generous.
# ``min_pinch_ready``: pinch_readiness score ≥ 0.10 (very easy).
_GRASP_CHECK_KWARGS = {
    "closed_threshold": 0.85,
    "gate_dist_m": 0.030,
    "width_frac": 0.30,
    "min_pinch_ready": 0.10,
    "width_weight": _SHORT_EDGE_WIDTH_WEIGHT,
    "thickness_sigma_m": 0.020,
    "min_finger_sep_m": 0.004,
    "pcb_half_thickness_m": PCB_Z * 0.5,
    "min_straddle_sep_m": _MIN_STRADDLE_SEP_M,
}

# Pinch orientation obs — minimum finger separation for valid cosines.
_PINCH_ORIENT_MIN_SEP_M = 0.004


def _pinch_orient_obs_params(**extra) -> dict:
    """Shared kwargs for ``pinch_orientation_cos`` policy observation."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "min_finger_sep_m": _PINCH_ORIENT_MIN_SEP_M,
        "push_axis_world": PUSH_AXIS_WORLD,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _grasp_entity_params(**extra) -> dict:
    """Common SceneEntityCfg + geometry keys for grasp reward terms."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "half_length_m": _HALF_LENGTH_M,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _grasp_orientation_base_params(**extra) -> dict:
    """Near-edge gate kwargs for top/bottom orientation rewards (no push axis)."""
    base = _grasp_entity_params(
        width_weight=_SHORT_EDGE_WIDTH_WEIGHT,
        gate_dist_m=0.08,   # wider active region so the rail-vertical reward persists on drift
        min_finger_sep_m=0.006,
    )
    base.update(extra)
    return base


def _grasp_between_fingers_params(**extra) -> dict:
    """Kwargs for pcb_between_gripper_fingers (straddle + proximity + width-centering, position only)."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "half_length_m": _HALF_LENGTH_M,
        "pcb_half_thickness_m": PCB_Z * 0.5,
        # Wide sigma: non-zero throughout full approach.  exp(-30mm/40mm) ≈ 0.47 at home pose.
        "proximity_sigma_m": 0.040,
        # Width-centring: 0.37 at 20 mm off, 0.78 at 5 mm off, 1.0 centred.
        "width_sigma_m": 0.020,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _grasp_closing_params(**extra) -> dict:
    """Kwargs for gripper_closing_reward — straddle-gated closing signal.

    Returns ``is_straddled * closedness`` so the reward is zero during the open-jaw approach
    and ramps up only once one jaw is on each face of the board (paired with a positive weight).
    """
    base = {
        "asset_cfg": _GRIPPER_JOINT,
        "open_width_m": _GRIPPER_OPEN_WIDTH_M,
        # Enable the straddle gate (w_left * w_right < 0 → close only when straddling).
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _grasp_finger_proximity_params(**extra) -> dict:
    """Kwargs for ungated per-finger tanh proximity to trailing-edge grasp targets (approach)."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "half_length_m": _HALF_LENGTH_M,
        "pcb_half_thickness_m": PCB_Z * 0.5,
        "std": 0.05,                  # loose → smooth long-range approach gradient
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _grasp_premature_close_params(**extra) -> dict:
    """Kwargs for premature_close_penalty (use with a negative weight)."""
    base = {
        "asset_cfg": _GRIPPER_JOINT,
        "open_width_m": _GRIPPER_OPEN_WIDTH_M,
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        **_gripper_kinematics_kwargs(),
    }
    base.update(extra)
    return base


def _grasp_termination_params(**extra) -> dict:
    """Entity + geometry kwargs shared by grasp-success and pre-grasp terminations."""
    base = {
        "pcb_cfg": _PCB_ENT,
        "left_finger_cfg": _LEFT_FINGER,
        "right_finger_cfg": _RIGHT_FINGER,
        "gripper_joint_cfg": _GRIPPER_JOINT,
        "half_length_m": _HALF_LENGTH_M,
        "half_width_m": _PCB_HALF_WIDTH_M,
        "open_width_m": _GRIPPER_OPEN_WIDTH_M,
        **_GRASP_CHECK_KWARGS,
        **_gripper_kinematics_kwargs(),
        "push_axis_world": PUSH_AXIS_WORLD,
    }
    base.update(extra)
    return base


@configclass
class WidowXPcbSceneCfg(InteractiveSceneCfg):
    """Scene assets for the WidowX PCB task.

    Contains ground, light, robot, PCB cuboid, and the static magazine + conveyor USD (single asset).
    """
    ground = AssetBaseCfg(prim_path="/World/defaultGroundPlane", spawn=sim_utils.GroundPlaneCfg())
    
    light = AssetBaseCfg(prim_path="/World/defaultLight", spawn=sim_utils.DistantLightCfg(intensity=3000.0))
    
    robot = ArticulationCfg(
        prim_path="{ENV_REGEX_NS}/Robot",
        spawn=sim_utils.UsdFileCfg(
            # Trossen AI WidowX Follower USD (stiffness/damping already baked in).
            usd_path=os.path.join(ASSET_DIR, "usd_model", "usd_robot", "wxai", "wxai_follower.usd"),
            rigid_props=sim_utils.RigidBodyPropertiesCfg(
                disable_gravity=False,
                max_depenetration_velocity=5.0,
            ),
            articulation_props=sim_utils.ArticulationRootPropertiesCfg(
                enabled_self_collisions=True,
                solver_position_iteration_count=8*4,
                solver_velocity_iteration_count=2*4,
            ),
        ),
        init_state=ArticulationCfg.InitialStateCfg(
            pos=_ROBOT_BASE_POS,
            rot=_ROBOT_BASE_ROT_WXYZ,
            joint_pos=_ROBOT_HOME_JOINT_POS,
        ),
        # wxai_follower.usd has PD gains baked in — use None to inherit from USD.
        actuators={
            "wxai_arm": ImplicitActuatorCfg(
                joint_names_expr=["joint_[0-5]"],
                stiffness=None,
                damping=None,
            ),
            # right_carriage_joint is a mimic joint in the USD (driven by left_carriage_joint).
            "wxai_gripper": ImplicitActuatorCfg(
                joint_names_expr=["left_carriage_joint"],
                stiffness=None,
                damping=None,
            ),
        },
        soft_joint_pos_limit_factor=1.0,
    )
    
    pcb = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/PCB",
        spawn=sim_utils.CuboidCfg(
            size=(PCB_X, PCB_Y, PCB_Z),
            rigid_props=sim_utils.RigidBodyPropertiesCfg(
                solver_position_iteration_count=8*4,
                solver_velocity_iteration_count=2*4,
                max_depenetration_velocity=0.5,
                max_linear_velocity=25.0,
                max_angular_velocity=720.0,
                linear_damping=0.25,
                angular_damping=0.35,
            ),
            collision_props=sim_utils.CollisionPropertiesCfg(
                # Larger contact band + small rest separation vs kinematic meshes reduces tunneling and
                # visible z-fighting / overlap with pcb_insertion_env.usd conveyor meshes.
                contact_offset=0.004,
                rest_offset=0.0012,
            ),
            physics_material=sim_utils.RigidBodyMaterialCfg(
                friction_combine_mode="multiply",
                restitution_combine_mode="multiply",
                static_friction=2.0,
                dynamic_friction=1.6,
                restitution=0.0,
            ),
            mass_props=sim_utils.MassPropertiesCfg(mass=1.0),
            visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.1, 0.4, 0.1)),
        ),
        # Flat on conveyor; front edge 20 mm before slot (see ``_PCB_INIT_POS``).
        init_state=RigidObjectCfg.InitialStateCfg(pos=_PCB_INIT_POS, rot=_PCB_INIT_ROT_WXYZ),
    )


    pcb_insertion_env = AssetBaseCfg(
        prim_path="{ENV_REGEX_NS}/Magazine",
        spawn=sim_utils.UsdFileCfg(
            # Generated by usd_model/env_v3/convert_to_usd.py from assembly_2.urdf.
            # Materials: SteelMaterial (magazine), BeltMaterial (side belts),
            #            StandMaterial (stand + frame).
            usd_path=os.path.join(ASSET_DIR, "usd_model", "usd_env", "pcb_insertion_env.usd"),

        ), 
        # Fixture pose: _MAG_POS = assembly root in world; -90 deg Z rotation (see FK comments above).
        init_state=AssetBaseCfg.InitialStateCfg(
            pos=_MAG_POS,
            rot=_MAG_ROT_WXYZ,
        ),
    )

@configclass
class ActionsCfg:
    """Policy action space: arm + parallel gripper (so the policy can close on the PCB edge)."""

    arm_action = mdp.JointPositionActionCfg(
        asset_name="robot",
        joint_names=["joint_[0-5]"],
        scale=1.0,
        use_default_offset=True,
    )
    
    gripper_action = mdp.JointPositionActionCfg(
        asset_name="robot",
        joint_names=["left_carriage_joint"],
        scale=1.0,
        use_default_offset=True,
    )


@configclass
class ObservationsCfg:
    """Observation groups exposed to the policy."""

    @configclass
    class PolicyCfg(ObservationGroupCfg):
        """Per-step policy observations: robot joints, PCB pose, EE (grip midpoint)."""
        joint_pos = ObservationTermCfg(func=mdp.joint_pos_rel)
        joint_vel = ObservationTermCfg(func=mdp.joint_vel_rel)

        object_pos = ObservationTermCfg(func=mdp.root_pos_w, params={"asset_cfg": SceneEntityCfg("pcb")})

        # EE: midpoint of WidowX AI jaw tips (gripper_left/right) — actual contact surface.
        ee_pos = ObservationTermCfg(
            func=gripper_midpoint_position_env,
            params={
                "left_finger_cfg": SceneEntityCfg("robot", body_names="gripper_left"),
                "right_finger_cfg": SceneEntityCfg("robot", body_names="gripper_right"),
                **_gripper_kinematics_kwargs(),
            },
        )
        # 0 = closed, 1 = open — explicit signal to learn approach-then-close-then-push.
        gripper_opening = ObservationTermCfg(
            func=gripper_opening_normalized,
            params={
                "asset_cfg": SceneEntityCfg("robot", joint_names=["left_carriage_joint"]),
                "open_width_m": _GRIPPER_OPEN_WIDTH_M,
            },
        )
        # Jaw mid vs PCB center along thickness (pinch alignment); helps learn close from top/bottom.
        ee_thickness_offset = ObservationTermCfg(
            func=gripper_mid_thickness_offset_obs,
            params={
                "pcb_cfg": SceneEntityCfg("pcb"),
                "left_finger_cfg": SceneEntityCfg("robot", body_names="gripper_left"),
                "right_finger_cfg": SceneEntityCfg("robot", body_names="gripper_right"),
                "scale_m": 0.012,
                **_gripper_kinematics_kwargs(),
            },
        )
        # Jaw rail ∥ world +Z; wrist→carriage line ∥ push axis (+Y).
        pinch_orientation_cos = ObservationTermCfg(
            func=gripper_pinch_orientation_cos_obs,
            params=_pinch_orient_obs_params(),
        )
        # Jaw mid vs trailing short-edge centre in PCB frame (along / width / thick).
        trailing_edge_error = ObservationTermCfg(
            func=gripper_trailing_edge_error_obs,
            params={
                **_grasp_entity_params(
                    scale_along_m=_HALF_LENGTH_M,
                    scale_width_m=_PCB_HALF_WIDTH_M,
                    scale_thick_m=0.050,
                ),
            },
        )
    policy: PolicyCfg = PolicyCfg()


@configclass
class _SafetyRewardsCfg:
    """Regularisation terms active in every phase."""

    action_rate_penalty = RewardTermCfg(func=action_rate_l2, weight=-0.001)
    above_floor = RewardTermCfg(
        func=pcb_height_below_reference,
        params={"pcb_cfg": _PCB_ENT, "min_height": _MIN_PCB_HEIGHT_ENV},
        weight=-18.0,
    )
    pcb_flat = RewardTermCfg(
        func=pcb_thickness_axis_tilt_penalty,
        params={"pcb_cfg": _PCB_ENT},
        weight=-12.0,
    )


@configclass
class RewardsGraspPhaseCfg():
    """Grasp phase reward stack.

    Signals on the gripper joint are cleanly separated so the closing gradient is strong and
    not diluted by the geometric straddle factors:

    * ``finger_proximity`` (weight 2.0): ungated dense approach signal.  Both jaws are pulled
      toward their ±½-thickness targets throughout the full approach.  Active from step 1.

    * ``jaw_rail_vertical`` (weight 2.5): orientation shaping so the jaw rail stays ∥ world +Z;
      corrects gravity sag early.

    * ``pcb_between_fingers`` (weight 80.0): straddle quality, **position only** — four
      multiplicative factors:
        1. ``is_graspable``  — hard gate: one jaw above, one below PCB thickness plane.
        2. ``between_jaws``  — hard gate: PCB centre within jaw-span projection.
        3. ``prox``          — smooth: both jaws near their ±½-thickness targets (σ=40 mm).
        4. ``width_centre``  — smooth: jaws centred on PCB short-edge centre (σ=20 mm).
      No closedness factor here — it would fight the grip once the jaws hug the board.

    * ``gripper_closing`` (weight +60.0): ``is_straddled × closedness``.  Zero during the
      open-jaw approach, then a strong, clean "close now" signal once one jaw is on each face.

    * ``premature_close`` (weight -8.0): ``(1 − is_straddled) × closedness``.  Penalty for
      closing before straddling.  Net gripper-joint gradient: −8·closedness when not straddled
      (stay open), +60·closedness when straddled (close firmly).

    * ``grasp_success_bonus`` (weight 15.0): sparse bonus for a held valid edge-centre pinch.
    """

    action_rate_penalty = RewardTermCfg(func=action_rate_l2, weight=-0.0002)

    # Dense approach gradient — ungated so learning starts immediately from the home pose.
    finger_proximity = RewardTermCfg(
        func=pcb_finger_object_proximity,
        params=_grasp_finger_proximity_params(),
        weight=2.0,
    )
    # Orientation — jaw rail ∥ world +Z.
    jaw_rail_vertical = RewardTermCfg(
        func=gripper_jaw_rail_vertical_shaping,
        params=_grasp_orientation_base_params(),
        weight=2.5,
    )
    # Straddle quality (position only, no closedness): straddle × span × approach × width-centering.
    pcb_between_fingers = RewardTermCfg(
        func=pcb_between_gripper_fingers,
        params=_grasp_between_fingers_params(),
        weight=100.0,
    )
    # Closing — gated on straddle.  Separate from position so the closing gradient is strong.
    gripper_closing = RewardTermCfg(
        func=gripper_closing_reward,
        params=_grasp_closing_params(),
        weight=15.0,
    )
    # Penalty for closing before straddling — fills the zero-gradient gap during approach.
    # Value = closedness when NOT straddled; paired with negative weight → stay open.
    premature_close = RewardTermCfg(
        func=premature_close_penalty,
        params=_grasp_premature_close_params(),
        weight=-8.0,
    )
    # Sparse success bonus for a completed, held pinch on the trailing edge centre.
    grasp_success_bonus = RewardTermCfg(
        func=grasp_success_bonus_reward,
        params=_grasp_termination_params(),
        weight=15.0,
    )
    # Penalize sliding the PCB toward the slot (+Y) during grasp — keep the board at the trailing edge.
    pcb_push_displacement = RewardTermCfg(
        func=pcb_push_axis_displacement_penalty,
        params={
            "pcb_cfg": _PCB_ENT,
            "initial_y_env": _PCB_INIT_POS[1],
            "max_displacement_m": _PCB_MAX_PUSH_DISPLACEMENT_M,
        },
        weight=-12.0,
    )


@configclass
class RewardsInsertPhaseCfg(_SafetyRewardsCfg):
    """Phase 2 — insert grasped PCB along +Y into the slot."""

    insert_axis_align = RewardTermCfg(
        func=pcb_long_axis_parallel_to_push_reward,
        params={"pcb_cfg": _PCB_ENT, "axis_world": PUSH_AXIS_WORLD},
        weight=2.0,
    )
    insert_y_toward_slot = RewardTermCfg(
        func=pcb_lin_vel_y_toward_lead_target_y,
        params={
            "pcb_cfg": _PCB_ENT,
            "half_length_m": _HALF_LENGTH_M,
            "target_lead_y_env": _SLOT_MOUTH_LEAD_TARGET_XYZ_ENV[1],
        },
        weight=35.0,
    )
    insertion_proximity = RewardTermCfg(
        func=pcb_leading_edge_insertion_proximity_reward,
        params={
            "pcb_cfg": _PCB_ENT,
            "half_length_m": _HALF_LENGTH_M,
            "target_lead_xyz_env": _SLOT_MOUTH_LEAD_TARGET_XYZ_ENV,
            "sigma_m": 0.06,
        },
        weight=6.0,
    )
    insertion_depth = RewardTermCfg(
        func=pcb_insertion_depth_reward,
        params={
            "pcb_cfg": _PCB_ENT,
            "half_length_m": _HALF_LENGTH_M,
            "slot_mouth_y_env": _SLOT_MOUTH_Y_ENV,
            "max_depth_m": 0.20,
        },
        weight=50.0,
    )
    lateral_slide_penalty = RewardTermCfg(
        func=pcb_horizontal_velocity_perpendicular_to_axis_penalty,
        params={"pcb_cfg": _PCB_ENT, "axis_world": PUSH_AXIS_WORLD},
        weight=-2.5,
    )


@configclass
class EventCfgGrasp:
    """Phase 1 reset: PCB on rail, gripper open, arm at home."""

    reset_pcb_on_conveyor = EventTermCfg(
        func=reset_pcb_on_guide_rails,
        mode="reset",
        params={
            "pcb_cfg": _PCB_ENT,
            "pos_env_local": _PCB_INIT_POS,
            "rot_wxyz": _PCB_INIT_ROT_WXYZ,
            "velocity_scale": 0.0,
        },
    )
    reset_robot_home = EventTermCfg(
        func=reset_robot_joints_to_values,
        mode="reset",
        params={
            "asset_cfg": _ROBOT_ENT,
            "joint_positions": _ROBOT_HOME_JOINT_POS,
            "velocity_scale": 0.0,
            "use_current_joint_pos": False,
        },
    )


@configclass
class EventCfgInsert:
    """Phase 2 reset: arm at home with closed gripper, PCB kinematically snapped to jaws."""

    reset_robot_grasp_hold = EventTermCfg(
        func=reset_robot_joints_to_values,
        mode="reset",
        params={
            "asset_cfg": _ROBOT_ENT,
            "joint_positions": _INSERT_INIT_JOINT_POS,
            "velocity_scale": 0.0,
            "use_current_joint_pos": False,
        },
    )
    snap_pcb_to_jaws = EventTermCfg(
        func=snap_pcb_root_to_short_edge_grasp,
        mode="reset",
        params={
            "pcb_cfg": _PCB_ENT,
            "left_finger_cfg": _LEFT_FINGER,
            "right_finger_cfg": _RIGHT_FINGER,
            "half_length_m": _HALF_LENGTH_M,
            "rot_wxyz": _PCB_INIT_ROT_WXYZ,
            "velocity_scale": 0.0,
            "min_center_z_env_local": _PCB_CENTER_Z_ENV,
            **_gripper_kinematics_kwargs(),
        },
    )


@configclass
class TerminationsSharedCfg:
    """Safety terminations shared by all variants."""

    time_out = TerminationTermCfg(func=mdp.time_out, time_out=True)
    pcb_tilt_excessive = TerminationTermCfg(
        func=pcb_tilt_beyond_limit,
        params={"pcb_cfg": _PCB_ENT, "max_tilt_penalty": 0.10},
    )
    pcb_long_axis_not_horizontal = TerminationTermCfg(
        func=pcb_long_axis_vertical_component_exceeds,
        params={"pcb_cfg": _PCB_ENT, "max_abs_z": 0.40},
    )
    pcb_fallen_below_rail = TerminationTermCfg(
        func=pcb_root_height_below_env_minimum,
        params={"pcb_cfg": _PCB_ENT, "min_height_env": _PCB_TERMINATE_MIN_HEIGHT_ENV},
    )
    pcb_dropped = TerminationTermCfg(
        func=pcb_dropped_from_gripper,
        params={
            "pcb_cfg": _PCB_ENT,
            "left_finger_cfg": _LEFT_FINGER,
            "right_finger_cfg": _RIGHT_FINGER,
            "check_grasp_geometry": False,
            "min_height": 0.025,
        },
    )
    pcb_moving_backward = TerminationTermCfg(
        func=pcb_moving_backward_termination,
        params={"pcb_cfg": _PCB_ENT, "backward_vel_threshold": -0.03, "min_steps": 20},
    )


@configclass
class TerminationsGraspCfg(TerminationsSharedCfg):
    """Pre-grasp PCB pose failures only.

    Grasp success does **not** terminate the episode: the policy should reach the grasp and *hold*
    it, so holding accumulates reward (``grasp_success_bonus``) up to time-out. Terminating on
    success would make stalling in a partial pose competitive with completing the grasp.
    """

    # Stricter than shared defaults; guard against the board tipping while the jaws approach.
    pcb_tilt_excessive = TerminationTermCfg(
        func=pcb_tilt_before_grasp_termination,
        params={**_grasp_termination_params(max_tilt_penalty=0.1)},
    )
    pcb_long_axis_not_horizontal = TerminationTermCfg(
        func=pcb_xy_plane_rotation_before_grasp_termination,
        params={
            **_grasp_termination_params(min_xy_alignment=0.995, axis_world=PUSH_AXIS_WORLD),
        },
    )


@configclass
class TerminationsInsertCfg(TerminationsSharedCfg):
    """Insert phase: stricter drop check once the policy should hold the board."""

    pcb_dropped = TerminationTermCfg(
        func=pcb_dropped_from_gripper,
        params={
            "pcb_cfg": _PCB_ENT,
            "left_finger_cfg": _LEFT_FINGER,
            "right_finger_cfg": _RIGHT_FINGER,
            "check_grasp_geometry": True,
            "min_height": 0.025,
            **_gripper_kinematics_kwargs(),
        },
    )


@configclass
class _WidowXPcbEnvCfgBase(ManagerBasedRLEnvCfg):
    """Shared scene, actions, observations, and simulation for all task variants."""

    scene: WidowXPcbSceneCfg = WidowXPcbSceneCfg(num_envs=2048, env_spacing=1.5)
    observations: ObservationsCfg = ObservationsCfg()
    actions: ActionsCfg = ActionsCfg()
    sim: sim_utils.SimulationCfg = sim_utils.SimulationCfg(
        dt=0.002,
        render_interval=1,
        physics_material=sim_utils.RigidBodyMaterialCfg(
            friction_combine_mode="multiply",
            restitution_combine_mode="multiply",
            static_friction=1.5,
            dynamic_friction=1.2,
            restitution=0.0,
        ),
        physx=sim_utils.PhysxCfg(
            enable_ccd=True,
            solve_articulation_contact_last=True,
            gpu_max_rigid_contact_count=2**22,
            gpu_max_rigid_patch_count=2**19,
        ),
    )

    def __post_init__(self):
        self.viewer.eye = (0.95, 0.95, 0.65)
        self.viewer.lookat = (0.25, 0.35, 0.08)
        self.decimation = 4
        self.sim.render_interval = self.decimation


@configclass
class WidowXPcbGraspEnvCfg(_WidowXPcbEnvCfgBase):
    """Phase 1 only: learn to grasp the trailing short-edge centre."""

    rewards: RewardsGraspPhaseCfg = RewardsGraspPhaseCfg()
    events: EventCfgGrasp = EventCfgGrasp()
    terminations: TerminationsGraspCfg = TerminationsGraspCfg()

    def __post_init__(self):
        super().__post_init__()
        self.episode_length_s = 8.0


@configclass
class WidowXPcbInsertEnvCfg(_WidowXPcbEnvCfgBase):
    """Phase 2 only: learn to insert a pre-grasped PCB into the slot (+Y)."""

    rewards: RewardsInsertPhaseCfg = RewardsInsertPhaseCfg()
    events: EventCfgInsert = EventCfgInsert()
    terminations: TerminationsInsertCfg = TerminationsInsertCfg()

    def __post_init__(self):
        super().__post_init__()
        self.episode_length_s = 12.0